{
    "type": "error",
    "data": "Error emitting table",
    "stack": "Traceback (most recent call last):\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/emit/parquet_table_emitter.py\", line 40, in emit\n    await self._storage.set(filename, data.to_parquet())\n                                      ^^^^^^^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pandas/util/_decorators.py\", line 333, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pandas/core/frame.py\", line 3113, in to_parquet\n    return to_parquet(\n           ^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pandas/io/parquet.py\", line 480, in to_parquet\n    impl.write(\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pandas/io/parquet.py\", line 190, in write\n    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pyarrow/table.pxi\", line 3874, in pyarrow.lib.Table.from_pandas\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pyarrow/pandas_compat.py\", line 611, in dataframe_to_arrays\n    arrays = [convert_column(c, f)\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pyarrow/pandas_compat.py\", line 611, in <listcomp>\n    arrays = [convert_column(c, f)\n              ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pyarrow/pandas_compat.py\", line 598, in convert_column\n    raise e\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/pyarrow/pandas_compat.py\", line 592, in convert_column\n    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"pyarrow/array.pxi\", line 340, in pyarrow.lib.array\n  File \"pyarrow/array.pxi\", line 86, in pyarrow.lib._ndarray_to_array\n  File \"pyarrow/error.pxi\", line 91, in pyarrow.lib.check_status\npyarrow.lib.ArrowInvalid: ('Can only convert 1-dimensional array values', 'Conversion failed for column description_embedding with type object')\n",
    "source": "('Can only convert 1-dimensional array values', 'Conversion failed for column description_embedding with type object')",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/run.py\", line 320, in run_pipeline\n    await inject_workflow_data_dependencies(workflow)\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/run.py\", line 256, in inject_workflow_data_dependencies\n    table = await load_table_from_storage(f\"{id}.parquet\")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/run.py\", line 242, in load_table_from_storage\n    raise ValueError(msg)\nValueError: Could not find create_final_entities.parquet in storage!\n",
    "source": "Could not find create_final_entities.parquet in storage!",
    "details": null
}