{"type": "error", "data": "Error executing verb \"text_embed\" in create_final_entities: list index out of range", "stack": "Traceback (most recent call last):\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/text_embed.py\", line 105, in text_embed\n    return await _text_embed_in_memory(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/text_embed.py\", line 130, in _text_embed_in_memory\n    result = await strategy_exec(texts, callbacks, cache, strategy_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py\", line 63, in run\n    embeddings = _reconstitute_embeddings(embeddings, input_sizes)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py\", line 172, in _reconstitute_embeddings\n    embedding = raw_embeddings[cursor]\n                ~~~~~~~~~~~~~~^^^^^^^^\nIndexError: list index out of range\n", "source": "list index out of range", "details": null}
{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/run.py\", line 323, in run_pipeline\n    result = await workflow.run(context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/miniconda3/envs/graph/lib/python3.11/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n             ^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/text_embed.py\", line 105, in text_embed\n    return await _text_embed_in_memory(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/text_embed.py\", line 130, in _text_embed_in_memory\n    result = await strategy_exec(texts, callbacks, cache, strategy_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py\", line 63, in run\n    embeddings = _reconstitute_embeddings(embeddings, input_sizes)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/autodl-tmp/GraphRAG-Local-UI/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py\", line 172, in _reconstitute_embeddings\n    embedding = raw_embeddings[cursor]\n                ~~~~~~~~~~~~~~^^^^^^^^\nIndexError: list index out of range\n", "source": "list index out of range", "details": null}
